# EXCEPTION CASE 20
try:
    raise
except:
    break
    print("exception")
else:
    print("no exception found")
