# EXCEPTION CASE 24
try:
    raise
except:
    return
    print("exception")
else:
    print("no exception found")
finally:
    break
    print("final output")

