# EXCEPTION CASE 26
try:
    raise
except:
    print("exception")
else:
    print("no exception found")
finally:
    return
    print("final output")
