# EXCEPTION CASE 23
try:
    return raise
except:
    print("exception")
else:
    print("no exception found")
finally:
    break
    print("final output")
