# EXCEPTION CASE 19
try:
    break
    raise
except:
    print("exception")
else:
    print("no exception found")

