# EXCEPTION CASE 22
try:
    raise
except:
    print("exception")
else:
    print("no exception found")
finally:
    break
    print("final output")
